New attempt to keep Travis builds below 50min

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -11,15 +11,13 @@ language: c++
 addons:
   apt:
     sources: 
+      - boost-latest
       - ubuntu-toolchain-r-test
     packages:
       - g++-5
       - gcc-5
       - g++-6
       - gcc-6
-
-      # Sequoia deps
-      - libtbb-dev
 
       # OpenCV deps
       - libjpeg-dev 
@@ -58,20 +56,20 @@ matrix:
       compiler: gcc
       env: CONFIG=Release CXX_COMPILER=g++-5 C_COMPILER=gcc-5
     
-    # Linux GCC 5.4 (RelWithDebInfo)
-    - os: linux
-      compiler: gcc
-      env: CONFIG=RelWithDebInfo CXX_COMPILER=g++-5 C_COMPILER=gcc-5
+    # # Linux GCC 5.4 (RelWithDebInfo)
+    # - os: linux
+    #   compiler: gcc
+    #   env: CONFIG=RelWithDebInfo CXX_COMPILER=g++-5 C_COMPILER=gcc-5
 
-    # Linux GCC 6.1 (Release)
-    - os: linux
-      compiler: gcc
-      env: CONFIG=Release CXX_COMPILER=g++-6 C_COMPILER=gcc-6
+    # # Linux GCC 6.1 (Release)
+    # - os: linux
+    #   compiler: gcc
+    #   env: CONFIG=Release CXX_COMPILER=g++-6 C_COMPILER=gcc-6
     
-    # Linux GCC 6.1 (RelWithDebInfo)
-    - os: linux
-      compiler: gcc
-      env: CONFIG=RelWithDebInfo CXX_COMPILER=g++-6 C_COMPILER=gcc-6
+    # # Linux GCC 6.1 (RelWithDebInfo)
+    # - os: linux
+    #   compiler: gcc
+    #   env: CONFIG=RelWithDebInfo CXX_COMPILER=g++-6 C_COMPILER=gcc-6
 
 
 # Cache external dependencies
@@ -82,20 +80,24 @@ cache:
     - ${TRAVIS_BUILD_DIR}/deps/install/glbinding-${GLBINDING_VERSION}
     - ${TRAVIS_BUILD_DIR}/deps/install/opencv-${OPENCV_VERSON}
 
-
-before_install:
-  # Setup the X-Server and initialize a virtual display
-  - export DISPLAY=:99.0
-  - |
-    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile       \
-                            --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
-  - sleep 3
-
 #===---------------------------------------------------------------------------------------------===
 #   Installing (external dependencies)
 #===---------------------------------------------------------------------------------------------===
 
+# The total build time has to be below 50 min to ensure Travis does not timeout!
+# Unfortunately, if we timeout the caches are not uploaded, we thus have to make sure to upload our
+# stuff before we get killed to have a better chance next time!
+
 install:
+  # Max time before Travis times out (50 min)
+  - export MAX_TIME=3000
+
+  # Time required by Sequioia (20 min)
+  - export BUILD_TIME=1200
+
+  # Current time
+  - export START_TIME=$(date +%s)
+
   # Create deps dir if not existing
   - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
   - mkdir -p ${DEPS_DIR}
@@ -113,79 +115,93 @@ install:
     CMAKE_INSTALL_DIR=${DEPS_DIR}/install/cmake-${CMAKE_VERSION}
     if [[ -z "$(ls -A ${CMAKE_INSTALL_DIR})" ]]; then
       CMAKE_SHORT_VERSION=${CMAKE_VERSION%.*}
-      { travis_retry wget                                                                          \
-        https://cmake.org/files/v${CMAKE_SHORT_VERSION}/cmake-${CMAKE_VERSION}.tar.gz; } || exit 1 
-      tar xfz cmake-${CMAKE_VERSION}.tar.gz
-      (cd cmake-${CMAKE_VERSION} && ./configure --prefix=${CMAKE_INSTALL_DIR} && make install)
+      CMAKE_URL=https://cmake.org/files/v${CMAKE_SHORT_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
+      mkdir -p ${CMAKE_INSTALL_DIR}
+      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} |                         \
+                   tar --strip-components=1 -xz -C ${CMAKE_INSTALL_DIR}
     fi
     export PATH="${CMAKE_INSTALL_DIR}/bin:${PATH}"
 
-  # Install OpenCV
-  - |
-    OPENCV_INSTALL_DIR=${DEPS_DIR}/install/opencv-${OPENCV_VERSON}
-    if [[ -z "$(ls -A ${OPENCV_INSTALL_DIR})" ]]; then
-      { travis_retry wget https://github.com/opencv/opencv/archive/${OPENCV_VERSON}.tar.gz; } ||   \
-        exit 1
-      tar xfz ${OPENCV_VERSON}.tar.gz
-      pushd $(pwd)
-      mkdir opencv-${OPENCV_VERSON}/build && cd opencv-${OPENCV_VERSON}/build
-      cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_PNG:BOOL=ON -DWITH_TIFF:BOOL=ON                   \
-               -DWITH_JPEG:BOOL=ON -DBUILD_opencv_core:BOOL=ON -DBUILD_opencv_highgui:BOOL=ON      \
-               -DBUILD_opencv_imgcodecs:BOOL=ON -DBUILD_opencv_imgproc:BOOL=ON                     \
-               -DCMAKE_INSTALL_PREFIX=${OPENCV_INSTALL_DIR}
-      make install
-      popd
-    fi
-    export OpenCV_DIR="${OPENCV_INSTALL_DIR}/share/OpenCV"
+  # # Install OpenCV
+  # - |
+  #   OPENCV_INSTALL_DIR=${DEPS_DIR}/install/opencv-${OPENCV_VERSON}
+  #   if [[ -z "$(ls -A ${OPENCV_INSTALL_DIR})" ]]; then
+  #     { travis_retry wget https://github.com/opencv/opencv/archive/${OPENCV_VERSON}.tar.gz; } ||   \
+  #       exit 1
+  #     tar xfz ${OPENCV_VERSON}.tar.gz
+  #     pushd $(pwd)
+  #     mkdir opencv-${OPENCV_VERSON}/build && cd opencv-${OPENCV_VERSON}/build
+  #     cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_PNG:BOOL=ON -DWITH_TIFF:BOOL=ON                   \
+  #              -DWITH_JPEG:BOOL=ON -DBUILD_opencv_core:BOOL=ON -DBUILD_opencv_highgui:BOOL=ON      \
+  #              -DBUILD_opencv_imgcodecs:BOOL=ON -DBUILD_opencv_imgproc:BOOL=ON                     \
+  #              -DCMAKE_INSTALL_PREFIX=${OPENCV_INSTALL_DIR}
+  #     make install
+  #     popd
+  #   fi
+  #   export OpenCV_DIR="${OPENCV_INSTALL_DIR}/share/OpenCV"
 
-  # Install glbinding
-  - |
-    GLBINDING_INSTALL_DIR=${DEPS_DIR}/install/glbinding-${GLBINDING_VERSION}
-    if [[ -z "$(ls -A ${GLBINDING_INSTALL_DIR})" ]]; then
-      { travis_retry wget                                                                          \
-        https://github.com/cginternals/glbinding/archive/v${GLBINDING_VERSION}.tar.gz; } || exit 1
-      tar xfz v${GLBINDING_VERSION}.tar.gz
-      pushd $(pwd)
-      mkdir glbinding-${GLBINDING_VERSION}/build && cd glbinding-${GLBINDING_VERSION}/build
-      cmake .. -DCMAKE_BUILD_TYPE=Release -DOPTION_BUILD_DOCS:BOOL=OFF                             \
-               -DOPTION_BUILD_EXAMPLES:BOOL=OFF -DOPTION_BUILD_TESTS:BOOL=OFF                      \
-               -DCMAKE_INSTALL_PREFIX=${GLBINDING_INSTALL_DIR}
-      make install
-      popd
-    fi
-    export GLBINDING_ROOT="${GLBINDING_INSTALL_DIR}"
+  # # Install glbinding
+  # - |
+  #   GLBINDING_INSTALL_DIR=${DEPS_DIR}/install/glbinding-${GLBINDING_VERSION}
+  #   if [[ -z "$(ls -A ${GLBINDING_INSTALL_DIR})" ]]; then
+  #     { travis_retry wget                                                                          \
+  #       https://github.com/cginternals/glbinding/archive/v${GLBINDING_VERSION}.tar.gz; } || exit 1
+  #     tar xfz v${GLBINDING_VERSION}.tar.gz
+  #     pushd $(pwd)
+  #     mkdir glbinding-${GLBINDING_VERSION}/build && cd glbinding-${GLBINDING_VERSION}/build
+  #     cmake .. -DCMAKE_BUILD_TYPE=Release -DOPTION_BUILD_DOCS:BOOL=OFF                             \
+  #              -DOPTION_BUILD_EXAMPLES:BOOL=OFF -DOPTION_BUILD_TESTS:BOOL=OFF                      \
+  #              -DCMAKE_INSTALL_PREFIX=${GLBINDING_INSTALL_DIR}
+  #     make install
+  #     popd
+  #   fi
+  #   export GLBINDING_ROOT="${GLBINDING_INSTALL_DIR}"
 
 
-  # Install boost
-  - |
-    BOOST_INSTALL_DIR=${DEPS_DIR}/install/boost-${BOOST_VERSION}
-    if [[ -z "$(ls -A ${BOOST_INSTALL_DIR})" ]]; then
+  # # Install boost
+  # - |
+  #   BOOST_INSTALL_DIR=${DEPS_DIR}/install/boost-${BOOST_VERSION}
+  #   if [[ -z "$(ls -A ${BOOST_INSTALL_DIR})" ]]; then
       
-      BOOST_URL=$(printf "http://sourceforge.net/projects/boost/files/boost/%s/boost_%s.tar.gz"    \
-                  ${BOOST_VERSION} ${BOOST_VERSION//\./_})
+  #     BOOST_URL=$(printf "http://sourceforge.net/projects/boost/files/boost/%s/boost_%s.tar.gz"    \
+  #                 ${BOOST_VERSION} ${BOOST_VERSION//\./_})
       
-      mkdir -p ${BOOST_INSTALL_DIR}
-      { travis_retry wget --quiet -O - ${BOOST_URL} |                                              \
-        tar --strip-components=1 -xz -C ${BOOST_INSTALL_DIR}; } || exit 1
+  #     mkdir -p ${BOOST_INSTALL_DIR}
+  #     { travis_retry wget --quiet -O - ${BOOST_URL} |                                              \
+  #       tar --strip-components=1 -xz -C ${BOOST_INSTALL_DIR}; } || exit 1
       
-      GCC_VERSION=$($CXX -dumpversion)
-      pushd $(pwd)
-      cd ${BOOST_INSTALL_DIR}
-      echo "using gcc : ${GCC_VERSION} : ${CXX} ;" > user-config.jam
-      ./bootstrap.sh
-      ./b2 -j2 --toolset=gcc-${GCC_VERSION} --prefix=${BOOST_INSTALL_DIR}                          \
-               --user-config=${BOOST_INSTALL_DIR}/user-config.jam                                  \
-               --with-thread                                                                       \
-               --with-date_time                                                                    \
-               --with-atomic                                                                       \
-               --with-chrono                                                                       \
-               --with-filesystem                                                                   \
-               --with-program_options                                                              \
-               --d+2 install
-      popd
-    fi
-    export BOOST_ROOT="${BOOST_INSTALL_DIR}"
+  #     GCC_VERSION=$($CXX -dumpversion)
+  #     pushd $(pwd)
+  #     cd ${BOOST_INSTALL_DIR}
+  #     echo "using gcc : ${GCC_VERSION} : ${CXX} ;" > user-config.jam
+  #     ./bootstrap.sh
+  #     ./b2 -j2 --toolset=gcc-${GCC_VERSION} --prefix=${BOOST_INSTALL_DIR}                          \
+  #              --user-config=${BOOST_INSTALL_DIR}/user-config.jam                                  \
+  #              --with-thread                                                                       \
+  #              --with-date_time                                                                    \
+  #              --with-atomic                                                                       \
+  #              --with-chrono                                                                       \
+  #              --with-filesystem                                                                   \
+  #              --with-program_options                                                              \
+  #              --d+2 install
+  #     popd
+  #   fi
+  #   export BOOST_ROOT="${BOOST_INSTALL_DIR}"
 
+  # If we have atleast 20 min left we attempt to build the main project otherwise we skip and 
+  # immediately upload the build dependencies
+  - |
+    ELAPSED_TIME=$(expr $(date +%s) - $START_TIME)
+    TIME_LEFT=$(expr $MAX_TIME - $ELAPSED_TIME)
+
+    printf "Elapsed time: %d m %ds\n" $(($ELAPSED_TIME%3600/60)) $(($ELAPSED_TIME%60))
+    printf "Time left: %d m %ds\n" $(($TIME_LEFT%3600/60)) $(($TIME_LEFT%60))
+
+    if [ $BUILD_TIME -lt $TIME_LEFT ]; then 
+      export RUN_BUILD=true
+    else
+      export RUN_BUILD=false
+    fi 
   - popd
 
 #===---------------------------------------------------------------------------------------------===
@@ -200,27 +216,31 @@ before_script:
   - $CC --version
   - $CXX --version
 
-  # Build sequoia
-  - pushd $(pwd)
-  - mkdir build && cd build
-  - |
-    cmake .. -DBOOST_ROOT:PATH=$BOOST_ROOT                                                         \
-             -DGLBINDING_ROOT:PATH=$GLBINDING_ROOT                                                 \
-             -DOpenCV_DIR:PATH=$OpenCV_DIR                                                         \
-             -DCMAKE_BUILD_TYPE=$CONFIG
-  - make
-  - popd
+  - echo $RUN_BUILD
+  # - |
+  #   if [ $RUN_BUILD = true ]; then
+  #     pushd $(pwd)
+  #     mkdir build && cd build
+  #     cmake .. -DBOOST_ROOT:PATH=$BOOST_ROOT                                                       \
+  #              -DGLBINDING_ROOT:PATH=$GLBINDING_ROOT                                               \
+  #              -DOpenCV_DIR:PATH=$OpenCV_DIR                                                       \
+  #              -DCMAKE_BUILD_TYPE=$CONFIG
+  #     make
+  #     popd
+  #   fi
 
 #===---------------------------------------------------------------------------------------------===
 #   Testing
-#===---------------------------------------------------------------------------------------------=== 
-
+#===---------------------------------------------------------------------------------------------===
 script:  
-  # sequoia-engine
-  - pushd $(pwd)
-  - cd build/sequoia-engine
-  - ctest -C ${CONFIG}  -E "GameTest|RenderGLTest" --output-on-failure --force-new-ctest-process
-  - popd
+  - echo $RUN_BUILD
+  # - |
+  #   if [ $RUN_BUILD = true ]; then
+  #     pushd $(pwd)
+  #     cd build/sequoia-engine
+  #     ctest -C ${CONFIG}  -E "GameTest|RenderGLTest" --output-on-failure --force-new-ctest-process
+  #     popd
+  #   fi
 
 notifications:
   on_success: never
